mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=chat
    - MYSQL_ROOT_PASSWORD=root
server:
  build: .
  ports:
    - 1030:1030
  links:
    - mysql
  environment:
    - MYSQL_URI=localhost
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=chat